### ISSUE TITLE
Single Path Functionality Broken

### ISSUE THREAD

**Issue by Hashfyre** [Hashfyre/pyzure-cli#18]
Right now enabling only a single leaf level command (one complete root to leaf path), while disabling others essentially gives the following error.

Example case: pyzure storage container create ...

``` python
Traceback (most recent call last):
  File "pyzure.py", line 67, in <module>
    main(sys.argv[1:])
  File "pyzure.py", line 55, in main
    options_first=True
  File "/usr/lib/python2.7/site-packages/docopt.py", line 560, in docopt
    pattern = parse_pattern(formal_usage(DocoptExit.usage), options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 373, in parse_pattern
    result = parse_expr(tokens, options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 413, in parse_atom
    result = pattern(*parse_expr(tokens, options))
  File "/usr/lib/python2.7/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/usr/lib/python2.7/site-packages/docopt.py", line 415, in parse_atom
    raise tokens.error("unmatched '%s'" % token)
docopt.DocoptLanguageError: unmatched '['
```

**Comment by Hashfyre** [comment]
Was being caused by the 'whitespace' atom-package not ignoring 'Whitespace only lines'. Now set to ignore, as docopts needs an indented whitespace line after the options: section.
