### ISSUE TITLE
Subcommands break if explicit '--help' or <command> not supplied

### ISSUE THREAD

**Issue by Hashfyre** [Hashfyre/pyzure-cli#19]
Case:

``` shell
python pyzure.py storage
```

Error:

``` python
{'--help': False,
 '<command>': [],
 'storage': True}
Traceback (most recent call last):
  File "pyzure.py", line 67, in <module>
    main(sys.argv[1:])
  File "pyzure.py", line 61, in main
    commands[command](argv)
  File "commands/storage.py", line 168, in main
    argv = [command] + args['<args>']
KeyError: '<args>'
```

**Comment by Hashfyre** [comment]
Doesn't happen on the top level command 'pyzure' though

Case:

``` shell
python pyzure.py
```

Output:

``` shell
usage: pyzure [-h|--help] [-v|--version] [<command> [<args>...]]

options:
    -h, --help
    -v, --version

commands:
    login       Command to login into your Windows Azure account
    logout      Command to logout of your Windows Azure account
    account     Commands to manage your account information and publish settings
    config      Commands to manage your local settings
    network     Commands to manage your networks
    service     Commands to manage your Cloud Services
    storage     Commands to manage your Storage objects
    vm          Commands to manage your Virtual Machines
```

**Comment by 5310** [comment]
Cannot reproduce. Please push your current local branch state, remote state is stale.

**Comment by Hashfyre** [comment]
[SOLVED]
The following check on dict.keys() solved the issue:

``` python
    if '<args>' in args.keys():
        argv = [command] + args['<args>']
    else:
        main(['--help'])
```
